---
apiVersion: v1
kind: Secret
metadata:
  name: lesson-158-private
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:roehrich-hpe/lesson-158-private.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACCVwikSHOjslFtimKXEDKy6ahjU7mia2/5WaYvwxSRAegAAAJj24g1X9uIN
    VwAAAAtzc2gtZWQyNTUxOQAAACCVwikSHOjslFtimKXEDKy6ahjU7mia2/5WaYvwxSRAeg
    AAAEDyqDBqVWJsPAkEuDkZPtpPdivHthwEZu/7VomVWySoyZXCKRIc6OyUW2KYpcQMrLpq
    GNTuaJrb/lZpi/DFJEB6AAAAE2FyZ29jZEBkZWFudGVzdC5jb20BAg==
    -----END OPENSSH PRIVATE KEY-----
  insecure: "false"
  enableLfs: "true"
